### ISSUE TITLE
Lockscreen keep turning off

### ISSUE THREAD

**Issue by razvanrjp** [gabrielsiu/StickyNote#3]
Good day. So I want to congratulate you for this tweak. It is very nice and I was looking for something like this.

What I have noticed is that the when I am writing a note, the screen is turning off after a few seconds and it requires to push the home button to continue writing.

Is there anyway to prevent the screen from turning off when the keybord is activated and writing within the StickyNote? It would be appreciated. Thank you and I wish you the best!

**Comment by gabrielsiu** [comment]
Hi, thank you for downloading my tweak! I am currently working on an update that includes the feature to disable the lock screen time-out when you are editing the sticky note.

**Comment by razvanrjp** [comment]
Nice! Thanks for the response. Your effort is appreciated. Take care!

**Comment by gabrielsiu** [comment]
Feature added in v1.1
